name: gym_routine_app
description: A simple Flutter app to manage gym routines.

# Versión de SDK de Flutter
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencias para Hive y Flutter
  hive: ^2.0.0
  hive_flutter: ^1.0.0

  # Dependencias estándar de Flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  # Dependencias para generar código
  build_runner: ^2.4.13
  hive_generator: ^1.1.1

flutter:
  uses-material-design: true
